### ISSUE TITLE
keypair: keynames will not match if user sets different keyname in YAML

### ISSUE THREAD

**Issue by smithfarm** [smithfarm/ceph-auto-aws#10]
The `keyname` stanza of the YAML defaults to the username, e.g.:

```
keyname: smithfarm
```

The `generate-keys.sh` script assumes the default and uses `$(whoami)` as the basis of the keyname.

If the user changes the keyname in the YAML to any value other than the username, node instantiation will fail.

**Comment by capri1989** [comment]
This one could be closed as it was fixed in the meanwhile

**Comment by smithfarm** [comment]
Fixed by #31
